apiVersion: apps/v1beta2
# Kubernetes versions after 1.9.0 should use apps/v1
# Kubernetes versions before 1.8.0 should use apps/v1beta1 or extensions/v1beta1
kind: Deployment
metadata:
  name: telegraf-ksm
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-ksm
  template:
    metadata:
      labels:
        app: telegraf-ksm
    spec:
      containers:
      - name: telegraf
        image: wavefront/telegraf
        env:
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy.default
        - name: INTERVAL
          value: 60s
        - name: METRIC_SOURCE_NAME
          value: kube-state-metrics
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: telegraf-d
          mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: telegraf-d
        projected:
          sources:
          - configMap:
              name: telegraf-ksm-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-ksm-config
  namespace: kube-system
data:
  prometheus.conf: |
    [[inputs.prometheus]]
      urls = ["http://kube-state-metrics:8080/metrics"]
      namedrop = ["kube_namespace_*"]

      [[inputs.prometheus.tags]]
        cluster = "CLUSTER_NAME"
